# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170525_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='permission',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Permission', verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x9d\x83\xe9\x99\x90'),
            preserve_default=False,
        ),
    ]
