# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170525_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='permission',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='permission',
            field=models.ManyToManyField(to='web.Permission', verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x9d\x83\xe9\x99\x90'),
        ),
    ]
