# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.GroupProfile', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe7\xbb\x84\xe5\x90\x8d'),
        ),
    ]
