from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^user/profile/(\d+)$', user_profile, name='user_profile'),
    url(r'^user/profile/update/(\d+)$', update_profile, name='update_profile'),
    url(r'^user/change/password/(\d+)$', change_password, name='change_password'),
    url(r'^view/user/list/$', view_user_list, name='view_user_list'),
    url(r'^view/user/profile/(\d+)$', view_user_profile, name='view_user_profile'),
    url(r'^update/user/profile/(\d+)$', update_user_profile, name='update_user_profile'),
    url(r'^user/reset/password/(\d+)$', reset_password, name='reset_password'),
    url(r'^user/alter/permisson/(\d+)$', alter_permisson, name='alter_permisson'),
    url(r'^add/user/$', add_user, name='add_user'),
    url(r'^delete/user/$', del_user, name='del_user'),
    url(r'^view/group/$', view_group, name='view_group'),
    url(r'^update/group/(\d+)$', update_group, name='update_group'),
    url(r'^add/group/$', add_group, name='add_group'),
    url(r'^delete/group/$', delete_group, name='delete_group'),
    url(r'^group/alter/permisson/(\d+)$', alter_group_permisson, name='alter_group_permisson'),
    url(r'^help/$', help, name='help'),
    url(r'^server/register/$', server_register, name="server_register"),
    url(r'^server/update/(\d+)$', server_update, name="server_update"),
    url(r'^server/salt/test/api/$', salt_test_api, name="salt_test_api"),
    url(r'^server/saltapi/$', saltapi, name="saltapi"),
    url(r'^server/details/$', server_list, name='server_list'),
    url(r'^servers/(\d+)$', servers, name='servers'),
    url(r'^remove/server/$', del_server, name="del_server"),
    url(r'^salt/key/$', salt_key, name="salt_key"),
    url(r'^salt/command/$', salt_command, name="salt_command"),
    url(r'^salt/filesend/$', salt_filesend, name="salt_filesend"),
    url(r'^ssh/$', web_ssh, name="web_ssh"),
    url(r'^save/cpu/$', save_cpudata, name="save_cpudata"),
]
